name: env-zeroshotclassification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - pandas=1.3.5
  - numpy=1.24.2
  - polars=0.16.9
  - rapidfuzz=2.13.7
  - scipy=1.10.1
  - feather-format=0.4.1
  - statistics=1.0.3.5
  - editdistance=0.6.2
  - textwrap3=0.9.2
  - sparse_dot_topn=0.3.1
  - transformers=4.26.1
  - streamlit=1.19.0
  - psutil=5.9.4
  - ray-all=2.3.0
  
#  - pytorch=1.13.1
  - pip
  - pip:
      - db-dtypes==1.0.4
      - scikit-learn==1.2.1
      - contractions==0.1.73
      - cloudscraper==1.2.69
      - sentencepiece==0.1.97
#      - transformers==4.26.1
